all:
  children:
    bastion:
      hosts:
        bastion_host:
          ansible_host: 51.250.6.203
          ansible_user: ubuntu

    web:
      hosts:
        web-a:
          ansible_host: 10.0.1.22
          ansible_user: ubuntu
        web-b:
          ansible_host: 10.0.2.30
          ansible_user: ubuntu
      vars:
        ansible_ssh_common_args: >-
          -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p ubuntu@51.250.6.203"

    prometheus:
      hosts:
        prometheus_host:
          ansible_host: 10.0.1.21
          ansible_user: ubuntu
      vars:
        ansible_ssh_common_args: >-
          -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p ubuntu@51.250.6.203"

    grafana:
      hosts:
        grafana_host:
          ansible_host: 10.0.10.33
          ansible_user: ubuntu
      vars:
        ansible_ssh_common_args: >-
          -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p ubuntu@51.250.6.203"

    elasticsearch:
      hosts:
        elasticsearch_host:
          ansible_host: 10.0.1.32
          ansible_user: ubuntu
      vars:
        ansible_ssh_common_args: >-
          -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p ubuntu@51.250.6.203"

    kibana:
      hosts:
        kibana_host:
          ansible_host: 10.0.10.10
          ansible_user: ubuntu
      vars:
        ansible_ssh_common_args: >-
          -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p ubuntu@51.250.6.203"

