---
- name: configure bastion
  hosts: bastion
  become: true

  tasks:
    - name: install htop
      ansible.builtin.apt:
        name:
          - htop
          - vim
          - fail2ban
          - git
        state: present
        update_cache: true
