---
- name: Prepare Prometheus configs (run on localhost)
  hosts: localhost
  gather_facts: false
  roles:
    - prometheus_setup

- name: Install Prometheus server
  hosts: prometheus_host
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - role: prometheus
      vars:
        prometheus_version: "3.5.3"
        prometheus_web_listen_address: "0.0.0.0:9090"
        prometheus_scrape_configs: "{{ hostvars['localhost'].prometheus_scrape_configs_final }}"

