{
 "title": "NGINX Logs",
 "description": "NGINX metrics with Prometheus for custom log parser. Vector example. Should also work with https://github.com/martin-helmich/prometheus-nginxlog-exporter\r\nDashboard is based on 15947.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance:",
    "query": {
     "query": "label_values(nginx_http_response_count_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Percentage Ratio of status codes to all status codes",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_count_total{status=~\"^2..\",instance=~\"$instance\"}[$__rate_interval])) / sum(rate(nginx_http_response_count_total{instance=~\"$instance\"}[$__rate_interval])) * 100",
     "legendFormat": "2** status codes"
    },
    {
     "expr": "sum(rate(nginx_http_response_count_total{status=~\"^4..\",instance=~\"$instance\"}[$__rate_interval])) / sum(rate(nginx_http_response_count_total{instance=~\"$instance\"}[$__rate_interval])) * 100",
     "legendFormat": "4** status codes"
    },
    {
     "expr": "sum(rate(nginx_http_response_count_total{status=~\"^5..\",instance=~\"$instance\"}[$__rate_interval])) / sum(rate(nginx_http_response_count_total{instance=~\"$instance\"}[$__rate_interval])) * 100",
     "legendFormat": "5** status codes"
    }
   ]
  },
  {
   "title": "HTTP Traffic (KB/s)",
   "type": "timeseries",
   "description": "Response sizes in bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_size_bytes{instance=~\"$instance\"}[$__rate_interval])) by (method) / 1024 or label_replace(sum(rate(nginx_http_response_size_bytes{instance=~\"$instance\"}[$__rate_interval])) / 1024, \"method\", \"Total\", \"\", \"\")",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Status codes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_count_total{instance=~\"$instance\"}[1m])) by (status)"
    }
   ]
  }
 ]
}